### PR TITLE
Fix the bump target for MacOS users.

### PR DESCRIPTION
**Pull request by jotes**
@abdul-rafiu can you take a look at this?
I can't test it on MacOS, but the command below seems to work on Ubuntu (creates a commit with bumped version and creates the tag):
```
make bump part=patch
```

### CODE REVIEW

**Comment by abdul-rafiu** [comment]
@jotes thank you!! I ll check this over the weekend.

**Comment by abdul-rafiu** [comment]
@jotes thank you!! I ll check this over the weekend.

**Comment by abdul-rafiu** [comment]
@jotes this is what happening when I run the following,

 $ make bump part=patch
docker run -v /Users/rafiu/OpenSource/django-cookies-samesite:/src -v ~/.gitconfig:/etc/gitconfig -w /src tomologic/bumpversion patch setup.cfg

It is not creating any commit.

**Comment by jotes** [comment]
hey @abdul-rafiu,
Unfortunately, I can't reproduce this issue on my machine :( I have a hunch that's somehow related to the file permissions (?) on macOS.

On my machine, bumpversion works like this:
```
☁  django-cookies-samesite [fix-release-process] make bump part=patch
docker run -v /home/jotes/code/django-cookies-samesite:/src -v ~/.gitconfig:/etc/gitconfig -w /src tomologic/bumpversion patch setup.cfg
☁  django-cookies-samesite [fix-release-process] git log --oneline | head -n1
f5f6565 Bump version: 0.6.4 → 0.6.5```
Can you check the permissions of `setup.cfg` file? Unfortunately, I work on Linux and that makes debugging macOS issues harder.

**Comment by arafiu-rpx** [comment]
@jotes  No issues. I'll work and fix this issue and let you know

**Comment by jotes** [comment]
I'm closing this PR because it looks stale.

**Pull request closed without merging**
