### PR TITLE
Black check format error, travis failure fix

### PR DESCRIPTION
**Pull request by abdul-rafiu**

### CODE REVIEW

**Comment by abdul-rafiu** [comment]
@jotes Merging this will fix the Travis CI Black check issue. So, merging it.

**Comment by jotes** [comment]
Hey, Thanks for the update, I'll release the version today and write how you can do this yourself (I don't want to be a bottleneck again :-).

**Comment by jotes** [comment]
@abdul-rafiu When you want to release a new version, you should checkout the master branch and run:
```
make bump part=(major|minor|patch)

# e.g.
make bump part=patch
```
This command automatically bumps up the version of the library and creates a tag. Push this tag to the origin and TravisCI will release the new version on Pypi.

**Comment by abdul-rafiu** [comment]
@jotes  Thank you will do that :)

**Pull request merged**
